config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :stores
  resources :articles

  root 'welcome#index'

    namespace :api do
      resources :stores
      resources :articles
    end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :store
  validates :name, presence: true,length: { minimum: 5 , maximum: 50}
  validates :description, presence: true,length: { minimum: 5 , maximum: 300}
  validates :price, presence: true
  validates :price , presence: true,numericality: true
  validates :total_in_shelf, presence: true,numericality: true
  validates :total_in_vault, presence: true,numericality: true
  validates :store_id,presence: true, numericality: true

end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  # validates_associated :articles
  validates :name, presence: true,length: { minimum: 5 , maximum: 50}
  validates :address, presence: true,length: { minimum: 5 , maximum: 300}
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  ActionController::Parameters.action_on_unpermitted_parameters = :raise

  rescue_from(ActionController::ParameterMissing) do |parameter_missing_exception|
    response = { success: false, error_code: 2001, error_msg: "parameter "+parameter_missing_exception.param.to_s+" is required" }
    respond_to do |format|
      format.json { render json: response, status: :bad_request }
    end
  end

  rescue_from(ActionController::UnpermittedParameters) do |non_permitted_parameter_exception|
    response = { success: false, error_code: 2002, error_msg: non_permitted_parameter_exception.to_s}
    respond_to do |format|
      format.json { render json: response, status: :bad_request }
    end
  end

  rescue_from(ActiveRecord::RecordNotFound) do |test|
    response = { success: false, error_code: 2003, error_msg: test.to_s}
    respond_to do |format|
      format.json { render json: response, status: :not_found }
    end
  end



  def index
    @articles = Article.all
    render json:{ success: true, articles:@articles}, status: :created
  end

  def create
    @article = Article.new(article_params)
    if @article.valid?
      @store = Store.find(params[:store_id])
      @article=@store.articles.create(article_params)
      if @article
        render json: { success: true, article:@article}, status: :created
      else
        render json: { success: false, error_code: 2004, error_msg: "error saving article" },status: :internal_server_error
      end
    else
      render json: { success: false, error_code: 2005, error_msg: @article.errors },status: :bad_request
    end
  end

  def show
    @article = Article.find(params[:id])
    if @article
      render json: { success: true, article:@article}, status: :ok
    end
  end

  def update
    @article = Article.find(params[:id])
    @articleTemp = Article.new(article_params)
    if @articleTemp.valid?
      @store = Store.find(params[:store_id])
      @article.store_id=@store.id
      if @article.update(article_params)
        render json: { success: true, article:@article}, status: :ok
      else
        render json: { success: false, error_code: 2006, error_msg: "error updating article" },status: :internal_server_error
      end
    else
      render json: { success: false, error_code: 2007, error_msg: @article.errors },status: :bad_request
    end


  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    render json: { success: true}, status: :ok
  end


  private
  def article_params
    params.require(:article).permit(:name,:description,:price,:total_in_shelf,:total_in_vault,:store_id)
  end

end

app/controllers/api/stores_controller.rb
class Api::StoresController < ApplicationController

  ActionController::Parameters.action_on_unpermitted_parameters = :raise

  rescue_from(ActionController::ParameterMissing) do |parameter_missing_exception|
    response = { success: false, error_code: 1001, error_msg: "parameter "+parameter_missing_exception.param.to_s+" is required" }
    respond_to do |format|
      format.json { render json: response, status: :bad_request }
    end
  end

  rescue_from(ActionController::UnpermittedParameters) do |non_permitted_parameter_exception|
    response = { success: false, error_code: 1002, error_msg: non_permitted_parameter_exception.to_s}
    respond_to do |format|
      format.json { render json: response, status: :bad_request }
    end
  end

  rescue_from(ActiveRecord::RecordNotFound) do
    response = { success: false, error_code: 1003, error_msg: 'store not found'}
    respond_to do |format|
      format.json { render json: response, status: :not_found }
    end
  end



  def index
    @stores = Store.all
    render json:{ success: true, stores:@stores}, status: :created
  end

  def create
    @store = Store.new(store_params)
    if @store.valid?
      if @store.save
        render json: { success: true, store:@store}, status: :created
        else
          render json: { success: false, error_code: 1000, error_msg: "error saving store" },status: :internal_server_error
        end
    else
      render json: { success: false, error_code: 1004, error_msg: @store.errors },status: :bad_request
    end
  end

  def show
    @store = Store.find(params[:id])
    if @store
      render json: { success: true, store:@store}, status: :ok
    end
  end

  def update
    @store = Store.find(params[:id])
    @storenew = Store.new(store_params)
    if @storenew.valid?
      if @store.update(store_params)
        render json: { success: true, store:@store}, status: :ok
      else
        render json: { success: false, error_code: 1005, error_msg: "error updating store" },status: :internal_server_error
      end
    end


  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    render json: { success: true}, status: :ok
  end


  private
  def store_params
    params.require(:store).permit(:name,:address)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @stores = Store.all
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect+params[:store_id]
    @stores = Store.all
    @store = Store.find(params[:store_id])
    @article = Article.new(article_params)
    @article.store_id=@store.id
    if @article.valid?
      @article.save(article_params)
      redirect_to @article
    else
        render 'new'
    end

  end

  def index
    @articles= Article.all
  end

  def show
    @article = Article.find(params[:id])
  end


  def edit
    @stores = Store.all
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @stores = Store.all
    @store = Store.find(params[:store_id])
    @article.store_id=@store.id

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end


  private
  def article_params
    params.require(:article).permit(:name,:description,:price,:total_in_shelf,:total_in_vault)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to @store
    else
      render 'new'
    end
  end

  def index
    @stores = Store.all
  end

def show
  @store = Store.find(params[:id])
end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])

    if @store.update(store_params)
      redirect_to @store
    else
      render 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    redirect_to stores_path
  end

private
def store_params
  params.require(:store).permit(:name,:address)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

app/helpers/api/stores_helper.rb
module Api::StoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<div class="row">

      <%= form_for :article, url: article_path(@article), method: :patch do |f| %>

          <% if @article.errors.any? %>
              <div id="error_explanation" class="col-md-4 col-lg-4 alert alert-danger" style="float:none; margin: 0 auto" >
                <ul>
                  <% @article.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
      <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
        <div class="panel-body" style=" text-align: left">

          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, {:class => "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, {:class => "form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :price %><br>
            <%= f.text_field :price , {:class => "form-control"}%>
          </div>
          <div class="form-group">
            <%= f.label :total_in_shelf %><br>
            <%= f.text_field :total_in_shelf , {:class => "form-control"}%>
          </div>
          <div class="form-group">
            <%= f.label :total_in_vault %><br>
            <%= f.text_field :total_in_vault, {:class => "form-control"} %>
          <div>

            </br>
            <div class="form-group">
            <%= f.label :store %>
            <select name="store_id" class="btn-default">
              <%= @stores.each do |store| %>
                  <option value="<%= store.id %>"><%= store.name %></option>
              <% end %>
            </select>
          </div>
            <div class="form-group">
              <%= f.submit 'Edit', {:class => "btn btn-success pull-right" }   %>
              <%= link_to 'Back', articles_path , {:class => "btn btn-default pull-left"} %>
          </div>
        </div>
      </div>
          </div>
      </div>
      <% end %>


</div>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
</br>
<table class="table table-hover" style="text-align: center">
  <tr style="text-align: center" class="active">
    <th style="text-align: center">name</th>
    <th style="text-align: center">description</th>
    <th style="text-align: center">price</th>
    <th style="text-align: center">in shelf</th>
    <th style="text-align: center">in vault</th>
    <th style="text-align: center">store</th>
    <th style="text-align: center">actions</th>
  </tr>

  <% @articles.each do |article| %>
      <tr style="text-align: center">
        <td><%= article.name%></td>
        <td><%= article.description%></td>
        <td><%= article.price%></td>
        <td><%= article.total_in_shelf%></td>
        <td><%= article.total_in_vault%></td>
        <td><%= article.store.name%></td>
        <td>
          <%= link_to article_path(article) ,{:class=> "btn btn-default btn-md"} do %>
              <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %>
          <%= link_to edit_article_path(article), {:class=> "btn btn-default btn-md"} do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <%= link_to article_path(article), method: :delete,:class=> "btn btn-default btn-md",data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end%>
          </td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Article', new_article_path,{:class => "btn btn-success" }  %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<div class="row">

</div>
<%= form_for :article, url: articles_path do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation" class="col-xs-4 col-sm-4 col-md-4 col-lg-4 alert alert-danger" style="float:none; margin: 0 auto">
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
      <div class="panel-body" style=" text-align: left">

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name , {:class => "form-control"} %>
        </div>

        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description ,{:class => "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :price %><br>
          <%= f.text_field :price , {:class => "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :total_in_shelf %><br>
          <%= f.text_field :total_in_shelf, {:class => "form-control"}  %>
        </div>
        <div class="form-group">
          <%= f.label :total_in_vault %><br>
          <%= f.text_field :total_in_vault, {:class => "form-control"}  %>
        </div>
        <div class="form-group">
          <%= f.label :store %>
          <select name="store_id">
            <%= @stores.each do |store| %>
                <option value="<%= store.id %>"><%= store.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <%= f.submit 'create store', {:class => "btn btn-success pull-right"}%>
          <%= link_to 'Back', articles_path ,{:class => "btn btn-default pull-left"}%>
        </div>

        </div>
      </div>

<% end %>

app/views/articles/show.html.erb
<h1>Article Details</h1>
<div class="row">
  <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
    <div class="panel-body" style=" text-align: center">
      <div class="form-group">
        <label>Name:</label>
        <label><%= @article.name%></label>
      </div>

        <div class="form-group">
        <label>Description:</label>
        <label><%= @article.description%></label>
        </div>

          <div class="form-group">
        <label>Price:</label>
        <label><%= @article.price%></label>
          </div>
            <div class="form-group">
        <label>total articles in shelf</label>
        <label><%= @article.total_in_shelf%></label>
            </div>
              <div class="form-group">
        <label>total articles in vault</label>
        <label><%= @article.total_in_vault%></label>
              </div>
                <div class="form-group">
        <label>Store</label>
        <label><%= @article.store.name%></label>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Back', articles_path ,{:class => "btn btn-default" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>TestProject</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Super Zapatos</a></li>
        <li><a href="/articles">Articles</a></li>
        <li><a href="/stores">Stores</a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>
<div id="main-container" class="container" style="background-color: white; padding-top: 70px">
  <div class="row" style="text-align: center">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

</br>
<div class="row">

  <%= form_for :store, url: store_path(@store), method: :patch do |f| %>

      <% if @store.errors.any? %>
          <div id="error_explanation" class="col-md-4 col-lg-4 alert alert-danger" style="float:none; margin: 0 auto" >
            <ul>
              <% @store.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
        <div class="panel-body" style=" text-align: left">

          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, {:class => "form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :address %><br>
            <%= f.text_area :address, {:class => "form-control"} %>
          </div>

          <div class="form-group" style="text-align: center">
            <%= f.submit 'edit Store', {:class => "btn btn-success pull-right"} %>
            <%= link_to 'Back', stores_path, {:class => "btn btn-default pull-left"} %>
          </div>


        </div>
      </div>
  <% end %>


</div>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table class="table table-hover" style="text-align: center">
  <tr style="text-align: center" class="active">
    <th style="text-align: center">name</th>
    <th style="text-align: center">address</th>
    <th style="text-align: center">Actions</th>
  </tr>

  <% @stores.each do |store| %>
      <tr style="text-align: center">
        <td><%= store.name%></td>
        <td><%= store.address%></td>
        <td>
          <%= link_to store_path(store), {:class=> "btn btn-default btn-md"} do %>
              <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %>
          <%= link_to edit_store_path(store), {:class=> "btn btn-default btn-md"} do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <%= link_to store_path(store),method: :delete, :class=> "btn btn-default btn-md", data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end%>
        </td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Store', new_store_path,{:class => "btn btn-success" } %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<div class="row">
  <%= form_for :store, url: stores_path do |f| %>

      <% if @store.errors.any? %>
          <div id="error_explanation" class="col-md-4 col-lg-4 alert alert-danger" style="float:none; margin: 0 auto">
            <ul>
              <% @store.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
        <div class="panel-body" style=" text-align: left">
          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name,{:class => "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.label :address %><br>
            <%= f.text_area :address ,{:class => "form-control"}%>
          </div>

          <div class="form-group">
            <%= f.submit 'create Store', {:class => "btn btn-success pull-right"} %>
            <%= link_to 'Back', stores_path, {:class => "btn btn-default pull-left"} %>
          </div>

        </div>
      </div>
  <% end %>
</div>

app/views/stores/show.html.erb
<h1>Store details</h1>

<div class="row">
  <div class="panel panel-default col-md-4 col-lg-4" style="float:none; margin: 0 auto">
    <div class="panel-body" style=" text-align: left">


          <div class="form-group">
            <label>Name:</label>
            <label><%=@store.name %></label>
          </div>
          <div class="form-group">
            <label>Address:</label>
            <label><%= @store.address%></label>
          </div>

          <div class="form-group" style="text-align: center">
            <%= link_to 'Edit', edit_store_path(@store),{:class=>"btn btn-success pull-right"} %>
            <%= link_to 'Back', stores_path ,{:class=>"btn btn-default pull-left"} %>
          </div>

    </div>
  </div>

</div>
</br>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
<div class="row">
  <div class="col-xs-2  col-sm-2 col-md-2 col-lg-2">
    <img src="/assets/logo.png" class="img-responsive"/>
  </div>
  <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
    <h1>Ruby On Rails Sample App</h1>
    <p>Simple web application for a CRUD set of operations for a store and articles in each store</p>
    <p>also an API is provided to expose CRUD functionality for the articles and stores</p>
    <a class="btn btn-info" href="/stores">TRY IT</a>
  </div>
</div>

    <div class="row">
      <p></p>
    </div>
  </div>
</div>